# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_tiny_lm_dsets": "02_data.coco.ipynb",
         "get_small_lm_dsets": "02_data.coco.ipynb"}

modules = ["data/coco.py"]

doc_url = "https://cwza.github.io/text_to_img/"

git_url = "https://github.com/cwza/text_to_img/tree/master/"

def custom_doc_links(name): return None
